CREATE DATABASE HETHONGMUABAN

USE HETHONGMUABAN
CREATE TABLE KHACHHANG(
ID_KH INT PRIMARY KEY,
HOTENKH NCHAR(20),
DIACHI NCHAR(50),
SDT CHAR(11),
)
CREATE TABLE NHANVIEN(
ID_NV INT PRIMARY KEY,
HOTENNV NCHAR(20),
DIACHINV NCHAR(50),
CHUCNANG NCHAR(15),
)
CREATE TABLE TAIKHOAN(
ID INT PRIMARY KEY,
USERNAME CHAR(20),
PASSWORD CHAR(10),
)
CREATE TABLE SANPHAM(
ID_SP INT PRIMARY KEY,
TENSP NCHAR(50),
DONGIA INT
)
CREATE TABLE DONHANG(
ID_DH INT PRIMARY KEY,
ID_KH INT,
ID_NV INT,
TONGTIEN INT
)
CREATE TABLE CT_DH(
ID_DH INT,
ID_SP INT,
SOLUONG INT
)
CREATE TABLE CHAMCONG(
ID_NV INT,
NGAYLAMVIEC DATE,
GIOBATDAU CHAR(10),
GIOKETTHUC CHAR(10)
)
ALTER TABLE CHAMCONG
ADD CONSTRAINT FK_CHAMCONGNHANVIEN
FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV);


USE HETHONGMUABAN
ALTER TABLE DONHANG
ADD CONSTRAINT FK_KHACHHANGDONHANG
FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH);

ALTER TABLE CT_DH
ADD CONSTRAINT FK_CTDHDH
FOREIGN KEY (ID_DH) REFERENCES DONHANG(ID_DH);

ALTER TABLE CT_DH
ADD CONSTRAINT FK_CTDHDH2
FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP);

ALTER TABLE DONHANG
ADD CONSTRAINT FK_NHANVIENDONHANG
FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV);

ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_KHACHHANGTAIKHOAN
FOREIGN KEY (ID) REFERENCES KHACHHANG(ID_KH);









